# Weather Dashboard
[[redirects]]
  from = "/apps/weather-dashboard/*"
  to = "https://your-weather-dashboard.netlify.app/:splat"
  status = 200
  force = true

# Example: Chat App
[[redirects]]
  from = "/apps/chat-app/*"
  to = "https://your-chat-app.netlify.app/:splat"
  status = 200
  force = true

# Example: Todo App
[[redirects]]
  from = "/apps/todo-app/*"
  to = "https://your-todo-app.netlify.app/:splat"
  status = 200
  force = true